import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import { motion } from "framer-motion"
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300&display=swap" rel="stylesheet"/>
      </Head>

      <Navbar />
      <div class = "flex h-screen">
        <div class = "m-auto">
      <div className = "text-center text-5xl block  bold text-[#64c297]">
        Welcome to the Tree of Life <br />
        Tree finder tool for optimal Carbon Sequestration < br />
        <Link href= "/">
				<button class=" my-10 py-3 w-64 text-xl text-white bg-[#64c297] rounded-2xl">Get Started</button>
        </Link>
        {/* <img src = "/carbonrodlogo.jpg" width = "100" height = "100" /> */}
        </div>
        </div>
        </div>
        <footer className = "w-full h-full fixed left-0 bottom-0 flex justify-center items-center -z-50">
        <img src= "/bg.png" alt='logo'  width="100%" height="full" className="absolute -bottom-5 left-0 " /></footer>
  
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
        
        </a>

      </footer> */}

    </div>
  )
}
